name: Build Doxygen

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Doxygen
      run: sudo apt-get install doxygen
    - name: Build Doxygen
      run: doxygen Doxyfile
    - name: Upload Doxygen
      uses: actions/upload-artifact@v2
      with:
        name: doxygen
        path: docs/html
